name:                core-interpreter
version:             0.1.0.0
license:             NCSA
author:              "CS 421 Course Staff"
maintainer:          "mattox@illinois.edu"
copyright:           ""

extra-source-files:
- README.md

description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- unordered-containers >= 0.2
- parsec

library:
  source-dirs: src

executables:
  core:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-interpreter

